version: "3.7"
services:
  web:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - ecommerce-network
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: e-commerce
      POSTGRES_PASSWORD: e-commerce
    ports:
      - "5432:5432"
    networks:
      - ecommerce-network
    volumes:
      - ecommerce-data:/var/lib/postgresql/data

networks:
  ecommerce-network:
    driver: bridge

volumes:
  ecommerce-data: